### PR TITLE
Fix source map file generating error

### LINKED ISSUE #93: Getting 404
When launching the app in production mode it throws the following :

> http://localhost:8080/var/containers/Bundle/Application/A416BAEF-F864-4A43-8620-6E49393EA3BB/Kanakol.app/www/plugins/sentry-cordova/dist/js/sentry-cordova.bundle.js.map
> Failed to load resource: the server responded with a status of 404 (Not Found)

I am using Ionic 3.9.2 along with cordova 7.1.0 

I've tested only in an iPhone device and got that error.

### LINKED ISSUE #113: ionic ios problem
When i run my app on ios and i generate an error  I showed this error

`Failed to load resource: the server responded with a status of 404 () ionic://localhost/plugins/sentry-cordova/dist/js/sentry-cordova.bundle.js.map`

this is my ionic configuration

No target specified for emulator. Deploying to iPhone-X, 12.1 simulator
logPath: /Users/iacotp/Develop/Ionic/TestV3/platforms/ios/cordova/console.log
MacTurri:TestV3 iacotp$ ionic info
✔ Gathering environment info - done!

Ionic:

```
   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-webview 3.1.1, (and 9 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.11.3 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS
   Xcode      : Xcode 10.1 Build version 10B61
```

sentry-cordova version 0.13.1

the same configuration work correctly on browser

this is my package.json

```
{
  "name": "com.gabrielegi.testv3",
  "version": "0.0.1",
  "author": "Gabriele Giacomo",
  "homepage": "http://www.nauticapps.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build",
    "ionic:serve": "node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js serve",
    "test": "karma start ./test-config/karma.conf.js",
    "test-ci": "karma start ./test-config/karma.conf.js --single-run",
    "test-coverage": "karma start ./test-config/karma.conf.js --coverage",
    "e2e": "npm run e2e-update && npm run e2e-test",
    "e2e-test": "protractor ./test-config/protractor.conf.js",
    "e2e-update": "webdriver-manager update --standalone false --gecko false"
  },
  "config": {
    "ionic_source_map_type": "cheap-source-map",
    "ionic_copy": "./config/copy.config.js",
    "ionic_generate_source_map": "true"
  },
  "dependencies": {
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@ionic-native/app-version": "^4.20.0",
    "@ionic-native/core": "^4.6.0",
    "@ionic-native/device": "^4.20.0",
    "@ionic-native/document-viewer": "^4.20.0",
    "@ionic-native/email-composer": "^4.20.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/file-opener": "^4.20.0",
    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/social-sharing": "^4.20.0",
    "@ionic-native/splash-screen": "^4.6.0",
    "@ionic-native/sqlite": "^4.20.0",
    "@ionic-native/status-bar": "^4.6.0",
    "@ionic/storage": "^2.1.3",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "@types/html2canvas": "0.0.35",
    "@types/jspdf": "^1.2.2",
    "@types/leaflet": "^1.2.6",
    "bignumber.js": "^8.0.2",
    "cordova-android": "7.0.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-email-composer": "^0.9.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-opener2": "^2.1.4",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-webview": "^3.1.1",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.4",
    "es6-promise-plugin": "^4.2.2",
    "html2canvas": "^1.0.0-alpha.12",
    "ionic-angular": "^3.9.2",
    "ionic-long-press": "^1.5.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "^3.0.0",
    "jspdf": "^1.5.3",
    "leaflet": "^1.3.1",
    "leaflet-tilelayer-mbtiles-ts": "^1.4.9",
    "moment": "^2.23.0",
    "promise-polyfill": "^7.1.2",
    "rxjs": "^5.5.8",
    "sentry-cordova": "^0.13.1",
    "sw-toolbox": "^3.6.0",
    "whatwg-fetch": "^2.0.4",
    "zone.js": "^0.8.25"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.1",
    "typescript": "^2.4.2"
  },
  "description": "Nautical Calculator Pro Ionic project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
      },
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-app-version": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-file": {},
      "cordova-plugin-file-opener2": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-email-composer": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "sentry-cordova": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  },
  "style": "dist/leaflet.css"
}
```

### LINKED ISSUE #163: sentry-cordova.bundle.js sourcemap reference generates Safari error
It looks like `sentry-cordova.bundle.js` that's generated in `platforms/ios/www/plugins/sentry-cordova/dist/js` has a reference to a source map:

`//# sourceMappingURL=sentry-cordova.bundle.js.map`

However, since that source map doesn't actually exist, it causes Safari to log an error in the console. I don't think it's fatal, but certainly annoying.

Would it make sense to either remove the source map reference, or just have the sentry-cordova.bundle.js.map properly copied into `platforms/ios/www/plugins/sentry-cordova/dist/js`?

(I'm not familiar with how to do the latter, unfortunately).

### PR DESCRIPTION
**Pull request by akshitkrnagpal**
This properly copies source map file to the correct build directory.
Sorry, I could only test this in ios device. But should work in Android too.

Fixes #113
Fixes #163
Fixes #93

### CODE REVIEW

**Comment by akshitkrnagpal** [comment]
@HazAT Any chance you can review it? 😄

**Comment by HazAT** [comment]
Sorry for the delay, does this mean the source map will be bundled with the app?

**Comment by HazAT** [comment]
I will merge and test it, thank you!

**Comment by akshitkrnagpal** [comment]
@HazAT 

I don't think the error is related to the change in this PR. Do you think you can check it? Thank you.
```
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
```

Would love to have this in a new version. ❤️

**Pull request merged**
