### PR TITLE
Feat: Sentry Replay

### PR DESCRIPTION
**Pull request by lucas-zimerman**
Sentry Replay is bundled with Sentry Cordova, but needs to be manually initialized, for example:

```JavaScript
    // Cordova is now initialized. Have fun!
    var Sentry = cordova.require("sentry-cordova.Sentry");
    Sentry.init({
         dsn: 'https://7e4fb5fbc26e4014acb13772e1782aea@o447951.ingest.sentry.io/5627302', 
         debug:true, 
         integrations: [ new Sentry.Replay({
            maskAllText: true,
            blockAllMedia: false,    
         }) ]
    });
```

Additional changes:

- Bump Sentry Javascript from 6.1.0 to 7.34.0
- Bump Sentry Android from 6.4.1 to 6.11.0
- Bump Sentry iOS from 6.2.1 to 7.27.1
- Fixed internal break changes that happened on the JavaScript SDK
- Refactor so the SDK follows the same implementation pattern as other SDKs like Capacitor/React Native
- Fixed tests

TODO: 

- [x] Remove dead code from cordova.ts
- [x] cleanup Sentry CordovaOptions

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
Sorry for extra lines on　build.yml, vscode decided to format that file (not sure if it's correct now or not)
At any case will undo it to not pollute this PR.

**Review by bruno-garcia — COMMENTED** [review]
Cool to see this works, but I'm concerned it's so many version behind.
If we have bug reports, we can't bump the JS SDK to get the fix?

**Comment by lucas-zimerman** [comment]
> 



> Cool to see this works, but I'm concerned it's so many version behind. If we have bug reports, we can't bump the JS SDK to get the fix?



> Cool to see this works, but I'm concerned it's so many version behind. If we have bug reports, we can't bump the JS SDK to get the fix?

About the issue with Replay: https://sentry.io/organizations/sentry-sdks/issues/3899108480/events/ae18a2d6bff74d08904b4284231c49f4/?project=5627302
I can't do a lot about it since it's inside of a private repro but I added a filter to not send this error to the users.

image

Maybe the issue here is that it tried to return the property target but it was not found, so it felt into the catch block that also tried to return the target, resulting on the same error.

NOTE: This error only happens when the main webpage is hidden.

**Comment by expcapitaldev** [comment]
hi, any updates here?

**Comment by expcapitaldev** [comment]
@lucas-zimerman  sorry  I tagged you, can you pls share information about merge?

**Comment by lucas-zimerman** [comment]
@expcapitaldev  We'll update the SDKs first on a new version and then afterwards conclude the Replay feature for Cordova

**Pull request closed without merging**
