### PR TITLE
build(internal): Switch to eslint

### PR DESCRIPTION
**Pull request by AbhiPrasad**
A couple things.

I removed synk, I think we are using dependabot for the org. We should switch to that.

I added yarn.lock to version control.

I removed tslint.

### CODE REVIEW

**Comment by AbhiPrasad** [comment]
I bumped the travis test to use Node 10.

I am scared, so please confirm if this won't break anything horribly.

**Review by jennmueng — APPROVED** [review]
Wow this has been a while. Tried it locally and LGTM.

**Review by bruno-garcia — APPROVED** [review]
LGTM

**Comment by AbhiPrasad** [comment]
Nice to see this pull through 😄

**Pull request merged**
